### ISSUE TITLE
Issue submitting a form

### ISSUE THREAD

**Issue by mareksuscak** [ScalaConsultants/recru-app#38]
"Anyway, I’ve chosen “Backend Climber” → Scala:4 → Akka:3 → Play:0 → Slick:2 → Spray:2 → and uploaded this CV: https://michalrus.com/cv"

**Comment by mareksuscak** [comment]
This might be related to #37. Michal didn't specify if he was submitting the form from mobile or a desktop browser.

**Comment by burczu** [comment]
This issue was on the backend side and was related to the configuration of the server (lack of Access-Control-Allow-Origin). It's now fixed.

**Comment by mareksuscak** [comment]
Thx for clarification @burczu. Closing this ticket.
