### ISSUE TITLE
Incorrect behavior for tab

### ISSUE THREAD

**Issue by note** [ScalaConsultants/recru-app#56]
I fill `type your name field` and press `Tab`. As a result page is getting scrolled to "other skill` field even though I have not even picked "my path" - therefore there are not specific skill listed (as you can see at attached file):
![screen shot 2017-04-11 at 10 28 31](https://cloud.githubusercontent.com/assets/345056/24899859/20d72e94-1ea2-11e7-9fdf-c0482be14177.png)

I think that `Tab` should work in similar way as `Enter` does now.

**Comment by Alwox** [comment]
Fixed
